//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelsOnDeals
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public int USER_IDN { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_FNAME { get; set; }
        public string USER_LNAME { get; set; }
        public string USER_PASSWORD { get; set; }
    }
}
