//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelsOnDeals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class USER_INFO
    {
        public int USER_IDN { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "This field is required.")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string USER_EMAIL { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "This field is required.")]
        public string USER_FNAME { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "This field is required.")]
        public string USER_LNAME { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "This field is required.")]
        [DataType(DataType.Password)]
        public string USER_PASSWORD { get; set; }

        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "This field is required.")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("USER_PASSWORD",ErrorMessage = "Password does not match, type again!")]
        public string ConfirmPassword { get; set; }
    }
}
